// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sync} from '../models';

export function Chdir():Promise<string>;

export function GetState():Promise<main.State>;

export function Lock():Promise<void>;

export function RLock():Promise<void>;

export function RLocker():Promise<sync.Locker>;

export function RUnlock():Promise<void>;

export function Run(arg1:main.TestParams):Promise<string>;

export function TryLock():Promise<boolean>;

export function TryRLock():Promise<boolean>;

export function Unlock():Promise<void>;

export function Unwatch():Promise<void>;

export function Watch(arg1:main.TestParams):Promise<string>;
