// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chdir() {
  return window['go']['main']['App']['Chdir']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function StartFSNotify(arg1) {
  return window['go']['main']['App']['StartFSNotify'](arg1);
}

export function StopFSNotify() {
  return window['go']['main']['App']['StopFSNotify']();
}
