// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chdir() {
  return window['go']['main']['App']['Chdir']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTestFuncs(arg1) {
  return window['go']['main']['App']['GetTestFuncs'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function Unwatch() {
  return window['go']['main']['App']['Unwatch']();
}

export function Watch(arg1) {
  return window['go']['main']['App']['Watch'](arg1);
}
