// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chdir():Promise<string>;

export function List():Promise<Array<string>>;

export function Run(arg1:main.TestParams):Promise<string>;
