// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chdir():Promise<string>;

export function List():Promise<main.State>;

export function Run(arg1:main.TestParams):Promise<string>;

export function Unwatch():Promise<void>;

export function Watch(arg1:main.TestParams):Promise<string>;
